FROM nginx:1.29.7
ADD https://raw.githubusercontent.com/e-shekharreddy/tf-crt-docker/refs/heads/main/docker.sh /tmp
# ADD sample.tar /tmp -> then it will untar the files like unzip the files from zip files